kimyatesti/Controllers/RoleAdminController.cs
using kimyatesti.identity;
using kimyatesti.Identity;
using kimyatesti.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kimyatesti.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleAdminController : Controller
    {
        private RoleManager<IdentityRole> roleManager;
        private UserManager<AppUser> userManager;

        public RoleAdminController()
        {
            roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new IdentityDataContext()));
            userManager = new UserManager<AppUser>(new UserStore<AppUser>(new IdentityDataContext()));
        }
        // GET: RoleAdmin
        public ActionResult Index()
        {
            return View(roleManager.Roles);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string name)
        {
            if (ModelState.IsValid)
            {
                var result = roleManager.Create(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public ActionResult Delete(string Id)
        {
            var role = roleManager.FindById(Id);
            if (role!=null)
            {
                var result = roleManager.Delete(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "Rol bulunamadı!"});
            }
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var role = roleManager.FindById(id);
            var members = new List<AppUser>();
            var nonMembers = new List<AppUser>();
            foreach (var user in userManager.Users.ToList())
            {
                var list = userManager.IsInRole(user.Id, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEditModel() { 
            Role = role,
            Members = members,
            NonMembers = nonMembers

            });
        }
        [HttpPost]
        public ActionResult Edit(RoleUpdateModel model)
        {
            IdentityResult result;

            if (ModelState.IsValid)
            {
                foreach (var userId in model.IdsToAdd??new string[] { })
                {
                    result = userManager.AddToRole(userId, model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                foreach (var userId in model.IdsToDelete?? new string[] { })
                {
                    result = userManager.RemoveFromRole(userId, model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                return RedirectToAction("Index");
            }
            return View("Error", new string[] { "Aranılan rol yok"});
        }
    }
}

kimyatesti/Views/RoleAdmin/Create.cshtml
@model string
@{
    ViewBag.Title = "Create";
}

<h2>Create Role</h2>
<hr />

@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Name</label>
        <input name="name" value="@Model" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
}

kimyatesti/Views/RoleAdmin/Edit.cshtml
@model kimyatesti.Models.RoleEditModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    <input type="hidden" name="roleName" value="@Model.Role.Name" />
    <input type="hidden" name="RoleId" value="@Model.Role.Id" />

    <div class="panel panel-primary">
        <div class="panel-heading">
            Add to @Model.Role.Name
        </div>
        <table class="table table-striped">
            @if (Model.NonMembers.Count() == 0)
            {
                <tr>
                    <td colspan="3">Aday kullanıcı yok!</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User Id </td>
                    <td>Role</td>
                </tr>
                foreach (var user in Model.NonMembers)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToAdd" value="@user.Id" />
                        </td>
                    </tr>
                }
            }
        </table>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">
            Remove from @Model.Role.Name
        </div>
        <table class="table table-striped">
            @if (Model.Members.Count() == 0)
            {
                <tr>
                    <td colspan="3">Role eklenmiş kullanıcı yok!</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User Id </td>
                    <td>Role</td>
                </tr>
                foreach (var user in Model.Members)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToDelete" value="@user.Id" />
                        </td>
                    </tr>
                }
            }
        </table>
    </div>

    <button type="submit" class="btn btn-primary">Kaydet</button>
}

kimyatesti/Views/RoleAdmin/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Roller
    </div>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="3">
                    Rol yok!
                </td>
            </tr>
        }
        else
        {
            foreach (var role in Model)
            {
                <tr>
                    <td>@role.Id</td>
                    <td>@role.Name</td>
                    <td>
                        @using (Html.BeginForm("Delete", "RoleAdmin", new { id = role.Id }))
                        {
                            @Html.ActionLink("Edit", "Edit", new { role.Id }, new { @class = "btn btn-primary btn-sm" })
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        }
                    </td>
                </tr>
            }

        }
    </table>
</div>